import type { SerializedWeights } from "./neuralNetwork";

/**
 * Pre-trained DQN weights for the Hard difficulty RL agent.
 * Generated by scripts/train.ts — do not edit manually.
 *
 * This is a placeholder. Run `npm run train:ai` to generate real weights.
 */
export const TRAINED_WEIGHTS: SerializedWeights | null = null;
